name: quassel-webserver
version: master
summary: A web server/client for Quassel
description: |
  A web client for Quassel (requires a running quasselcore)

grade: devel
confinement: strict

apps:
  server:
    command: node $SNAP/lib/node_modules/quassel-webserver/app.js
    plugs: [network, network-bind]
    daemo: simple

parts:
  quassel-webserver:
    source: .
    plugin: nodejs
